
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost/mybatis_learning?serverTimezone=Asia/Shanghai
    username: root
    password: root


# MyBatis配置
mybatis:
  # SQL映射文件路径，classpath相对路径
  mapper-locations: mapper/*.xml
  # 类型别名包
  type-aliases-package: com.tcl.msb.entity